#!/bin/bash

. ltefi_md_git.in

main() {
	local PRO_PATH="histb_project_$(date | awk -F ' ' '{print $2$3}')"
	local user=$(whoami)

	mkdir -p ../${PRO_PATH}
	cp list.in ../${PRO_PATH}/list.in
	cp check_script.sh ../${PRO_PATH}/
	pushd ../${PRO_PATH}
	echo "#### PROJECT PATH: $(pwd) ####"


	git_clone_md ${user}
	git_clone_md_release ${user}
	git_clone_md_custom ${user}
	git_clone_md_capp ${user}
	git_clone_ap ${user}

	git clone https://github.com/smallcapp/capp

	popd
	exit 0
}

main
