#!/bin/bash

. ltefi_md_git.in

main() {
	local PRO_PATH="histb_project_v2_$(date | awk -F ' ' '{print $2$3}')"
	local user=$(whoami)

	mkdir -p ../${PRO_PATH}
	cp list_v2.in ../${PRO_PATH}/list.in
	cp check_script.sh ../${PRO_PATH}/
	pushd ../${PRO_PATH}
	echo "#### PROJECT PATH: $(pwd) ####"


	git_clone_md_v2 ${user}
	git_clone_md_release_v2 ${user}
	git_clone_md_custom_v2 ${user}
	git_clone_ap_v2 ${user}
	
	popd
	exit 0
}

main
